//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testsql.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class category
    {
        public category()
        {
            this.products = new HashSet<product>();
            this.productCates = new HashSet<productCate>();
        }
    
        public int idcate { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<product> products { get; set; }
        public virtual ICollection<productCate> productCates { get; set; }
    }
}
