//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testsql.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public customer()
        {
            this.orders = new HashSet<order>();
            this.services = new HashSet<service>();
        }
    
        public int Idcus { get; set; }
        public string namecus { get; set; }
        public int phonecus { get; set; }
        public string emailcus { get; set; }
        public string username { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<order> orders { get; set; }
        public virtual ICollection<service> services { get; set; }
    }
}
