//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testsql.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public order()
        {
            this.orderdetails = new HashSet<orderdetail>();
        }
    
        public int id_order { get; set; }
        public System.DateTime dateorder { get; set; }
        public int idcus { get; set; }
        public bool status { get; set; }
        public double total_amount { get; set; }
        public string paymentmethod { get; set; }
        public string shippingmethod { get; set; }
        public string shippingaddress { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual ICollection<orderdetail> orderdetails { get; set; }
    }
}
