//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testsql.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderdetail
    {
        public int id_detail { get; set; }
        public int idproduct { get; set; }
        public int idorder { get; set; }
        public int quantity { get; set; }
        public double price { get; set; }
        public double total_price { get; set; }
        public string bill_code { get; set; }
    
        public virtual order order { get; set; }
        public virtual product product { get; set; }
    }
}
