//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testsql.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public product()
        {
            this.orderdetails = new HashSet<orderdetail>();
        }
    
        public int id_product { get; set; }
        public string nameprod { get; set; }
        public string brand { get; set; }
        public int idcate { get; set; }
        public int price { get; set; }
        public int stock_quantity { get; set; }
        public string image { get; set; }
        public string description { get; set; }
    
        public virtual category category { get; set; }
        public virtual ICollection<orderdetail> orderdetails { get; set; }
    }
}
