//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testsql.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class service
    {
        public int id_service { get; set; }
        public string name_service { get; set; }
        public double price { get; set; }
        public string description { get; set; }
        public int idcus { get; set; }
    
        public virtual customer customer { get; set; }
    }
}
