//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testsql.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.customers = new HashSet<customer>();
        }
    
        public string username { get; set; }
        public string password { get; set; }
        public bool permission { get; set; }
    
        public virtual ICollection<customer> customers { get; set; }
    }
}
